// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabD5oXeul-moQqHo_QRlgiw_2tD9ROdA',
    appId: '1:172116184627:web:7706665f658888942d9d46',
    messagingSenderId: '172116184627',
    projectId: 'seproject-713',
    authDomain: 'seproject-713.firebaseapp.com',
    storageBucket: 'seproject-713.firebasestorage.app',
    measurementId: 'G-8GBN4EFR3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNU-ljF2G4G0jcMwDuGYzauR4NOayXEI',
    appId: '1:172116184627:android:5590f344fecb3cdf2d9d46',
    messagingSenderId: '172116184627',
    projectId: 'seproject-713',
    storageBucket: 'seproject-713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmf3Cg_kn0NEujcwZYlZU_0lAsko5smp8',
    appId: '1:172116184627:ios:d1c13d0419493e3b2d9d46',
    messagingSenderId: '172116184627',
    projectId: 'seproject-713',
    storageBucket: 'seproject-713.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmf3Cg_kn0NEujcwZYlZU_0lAsko5smp8',
    appId: '1:172116184627:ios:d1c13d0419493e3b2d9d46',
    messagingSenderId: '172116184627',
    projectId: 'seproject-713',
    storageBucket: 'seproject-713.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabD5oXeul-moQqHo_QRlgiw_2tD9ROdA',
    appId: '1:172116184627:web:91271faec6a7514c2d9d46',
    messagingSenderId: '172116184627',
    projectId: 'seproject-713',
    authDomain: 'seproject-713.firebaseapp.com',
    storageBucket: 'seproject-713.firebasestorage.app',
    measurementId: 'G-E6R4EV2SJ2',
  );
}
